---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian9
    image: debian:9
  - name: centos8
    image: centos:8
provisioner:
  name: ansible
verifier:
  name: testinfra
